name: Test Self-Hosted Runner

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Test runner
        run: |
          echo "✅ Self-hosted runner is working!"
          echo "Runner: $(hostname)"
          echo "OS: $(uname -a)"
          docker --version
